feature-36-home-lambda-api-spec-for-memo-management
Metatavu/home-lambdas-API-spec pull request #37
Opened 2024-11-03 23:22 UTC by DZotoff

2024-11-06 08:12 UTC, Jdallos requested changes

2024-11-06 08:12 UTC, Jdallos commented on swagger.yaml
> +          description: Failed to create comment.
I think the best option is to have a generic "default" error response like we do for other end points rather than specifying particular error statuses. Here is what we are using already:

      "default":
          description: Invalid request was sent to the server.
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Error"
                  
I'd suggest replacing all 400 and 500 responses like you have done here with this.

2024-11-06 08:12 UTC, Jdallos commented on swagger.yaml
> +  "/card-comments":
Id suggest having it as trello/card-comments. Similar for google drive related endpoints also.

2024-11-06 08:12 UTC, Jdallos commented on swagger.yaml
> +  "/card-comments":
Let me know what you think, if you agree this should be applied to all relevant endpoints

2024-11-06 08:12 UTC, Jdallos commented on swagger.yaml
> +                    type: string
Probably worth making a TrelloCard schema for this

2024-11-06 08:12 UTC, Jdallos commented on swagger.yaml
> +    post:
Throughout the spec we typically order the get (list) and then post (create) for a given endpoint. Can you make sure where relevant you order your new endpoints in the same way- it just makes it easier to check the spec as it grows.

2024-11-06 08:12 UTC, Jdallos commented on swagger.yaml
> +                    type: string
Actually it seems you already have created the schema Card. So it should be referenced here also

2024-11-06 08:12 UTC, Jdallos commented on swagger.yaml
> +
```suggestion
```

2024-11-06 08:12 UTC, Jdallos commented on swagger.yaml
> +  "/card/{id}":
Typically we would want the card endpoints to be grouped together, so this card/{id} should come straight after / card

2024-11-06 08:12 UTC, Jdallos commented on swagger.yaml
> +    Card:
Consider whether these schemas should be named more specifically e.g. googleDriveMemo, TrelloCard, TrelloMember. It's your call

2024-11-06 18:43 UTC, DZotoff commented on swagger.yaml
> +          description: Failed to create comment.
Return type of functions is a single object, why is an array used here?

2024-11-07 06:40 UTC, Jdallos commented on swagger.yaml
> +          description: Failed to create comment.
Well spotted, I've updated the code snippet so it's now correct. Not sure how or when that crept in, feel free to update by removing the
type: array
items:
lines from other default error responses in the spec.

2024-11-07 06:44 UTC, Jdallos approved these changes

2024-11-18 13:12 UTC, merged