Forecast cleaning
Metatavu/home-lambdas-API-spec pull request #64
Opened 2024-12-13 08:15 UTC by McDuuck

2024-12-13 19:20 UTC, Hanhz2707 approved these changes

2024-12-19 08:16 UTC, Jdallos requested changes

2024-12-19 08:16 UTC, Jdallos commented on swagger.yaml
> -                  $ref: "#/components/schemas/Allocations"
Rememeber to also remove all the related schemas

2025-01-02 09:54 UTC, Jdallos approved these changes

2025-01-02 10:09 UTC, merged